### ISSUE TITLE
not compiling in openframeworks 0.9

### ISSUE THREAD

**Issue by joaodafonseca** [gauthiier/ofxiPhoneSerial#1]
Hi there, 

Any idea how to compile the addon on OF 0.9?

thanks

**Comment by gauthiier** [comment]
Unfortunately no. I've never tried. The addon was written for iPhone 4 with special Redpark TTL cable (circa 2011-2012). I presume porting it to newer devices (with newer Redpark cable + newer Redpark SDK) may be feasible, but I'm not set up here with such things.

**Comment by joaodafonseca** [comment]
ok, thanks will have a look
